# var/config/config.yml

parameter_integer: 4004
parameter_string: 'originString'
parameter_array: ['a', 'b', 'c']
parameter_remove: 'will_be_removed'
parameter_it_has: 'it has'
parameter_Case_Sensitive: 'insensitive'
parameter_strict: 'strict'
parameter_strict_null: null
parameter_strict_by_type_integer: 10
parameter_strict_by_type_string: 'my-string'
parameter_strict_by_type_array: ['a', 'b', 'c']
parameter_strict_by_type_error: ['y']